import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import { Check, Copy, Download, Link as LinkIcon } from 'lucide-react';
import { ConsoleSection } from './ConsoleSection';
import { CodeBlock } from './CodeBlock';
import { useMenuSound } from '../hooks/useMenuSound';
import { createGitHubGist, persistGitHubToken, readGitHubToken } from '../utils/github';
import {
  configGroups,
  type ConfigBlock,
} from '../data/configBlocks';

const allBlocks = configGroups.flatMap((group) => group.blocks);
const allBlockIds = new Set(allBlocks.map((block) => block.id));
const defaultSelectedIds = allBlocks
  .filter((block) => block.defaultEnabled)
  .map((block) => block.id);

const buildPreviewContent = (blocks: ConfigBlock[]) => {
  if (!blocks.length) {
    return '';
  }

  return blocks
    .map((block) => `// === ${block.label} ===\n${block.code.trim()}`)
    .join('\n\n');
};

const buildDownloadContent = (blocks: ConfigBlock[]) => {
  const header = [
    '// Generated by CS 1.6 Config Wiki',
    `// Build: ${new Date().toISOString()}`,
    '',
  ].join('\n');

  const body = buildPreviewContent(blocks);
  return `${header}${body ? `\n${body}` : ''}\n`;
};

const generateFileName = () => {
  const uuid =
    typeof crypto !== 'undefined' && 'randomUUID' in crypto
      ? crypto.randomUUID()
      : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
  return `cs16-${uuid}.cfg`;
};

const sanitizeFileName = (value?: string | null) => {
  if (!value) {
    return null;
  }

  const trimmed = value.trim();
  if (!trimmed) {
    return null;
  }

  const cleaned = trimmed
    .replace(/\.cfg$/i, '')
    .replace(/[^a-zA-Z0-9-_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  if (!cleaned) {
    return null;
  }

  return `${cleaned.slice(0, 48)}.cfg`;
};

const toDataUrl = (content: string) =>
  `data:text/plain;charset=utf-8,${encodeURIComponent(content)}`;

const createShareUrl = (ids: string[], name: string) => {
  if (typeof window === 'undefined') {
    return '';
  }

  const url = new URL(window.location.href);
  url.searchParams.set('preset', ids.join(','));
  url.searchParams.set('name', name);
  url.searchParams.set('download', '1');
  return url.toString();
};


export function ConfigBuilder() {
  const { playSelect } = useMenuSound();
  const [selectedIds, setSelectedIds] = useState<Set<string>>(
    () => new Set(defaultSelectedIds),
  );
  const [fileName, setFileName] = useState<string | null>(null);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [githubToken, setGithubToken] = useState(() => readGitHubToken());
  const [githubRawUrl, setGithubRawUrl] = useState<string | null>(null);
  const [githubViewUrl, setGithubViewUrl] = useState<string | null>(null);
  const [githubError, setGithubError] = useState<string | null>(null);
  const [isPublishing, setIsPublishing] = useState(false);
  const [copiedExec, setCopiedExec] = useState(false);
  const [copiedShare, setCopiedShare] = useState(false);
  const [copiedGitHub, setCopiedGitHub] = useState(false);
  const [autoDownload, setAutoDownload] = useState(false);
  const [presetName, setPresetName] = useState<string | null>(null);
  const autoGeneratedRef = useRef(false);

  const selectedBlocks = useMemo(
    () => allBlocks.filter((block) => selectedIds.has(block.id)),
    [selectedIds],
  );

  const hasSelection = selectedBlocks.length > 0;
  const previewContent = useMemo(
    () => buildPreviewContent(selectedBlocks),
    [selectedBlocks],
  );

  const buildOutput = useCallback(
    (overrideName?: string, fallbackName?: string | null) => {
      if (!selectedBlocks.length) {
        return null;
      }

      const chosenName =
        sanitizeFileName(overrideName) ?? (fallbackName ?? generateFileName());
      const content = buildDownloadContent(selectedBlocks);
      const dataUrl = toDataUrl(content);
      const nextShareUrl = createShareUrl(
        selectedBlocks.map((block) => block.id),
        chosenName,
      );

      setFileName(chosenName);
      setDownloadUrl(dataUrl);
      setShareUrl(nextShareUrl);

      return {
        chosenName,
        content,
        dataUrl,
        shareUrl: nextShareUrl,
      };
    },
    [selectedBlocks],
  );

  const handleGenerate = useCallback(
    (overrideName?: string, auto = false) => {
      const output = buildOutput(overrideName, null);
      if (!output) {
        return;
      }

      if (auto) {
        const anchor = document.createElement('a');
        anchor.href = output.dataUrl;
        anchor.download = output.chosenName;
        anchor.rel = 'noopener';
        anchor.click();
      } else {
        playSelect();
      }
    },
    [buildOutput, playSelect],
  );

  const handleToggle = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
    playSelect();
  };

  const handleSelectAll = () => {
    setSelectedIds(new Set(allBlocks.map((block) => block.id)));
    playSelect();
  };

  const handleClear = () => {
    setSelectedIds(new Set());
    playSelect();
  };

  const handleCopyExec = async () => {
    if (!fileName) {
      return;
    }

    try {
      await navigator.clipboard.writeText(`exec ${fileName}`);
      setCopiedExec(true);
      setTimeout(() => setCopiedExec(false), 2000);
      playSelect();
    } catch (err) {
      console.error('Failed to copy exec command:', err);
    }
  };

  const handleCopyShare = async () => {
    if (!shareUrl) {
      return;
    }

    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopiedShare(true);
      setTimeout(() => setCopiedShare(false), 2000);
      playSelect();
    } catch (err) {
      console.error('Failed to copy share link:', err);
    }
  };

  const handleCopyGitHub = async () => {
    if (!githubRawUrl) {
      return;
    }

    try {
      await navigator.clipboard.writeText(githubRawUrl);
      setCopiedGitHub(true);
      setTimeout(() => setCopiedGitHub(false), 2000);
      playSelect();
    } catch (err) {
      console.error('Failed to copy GitHub link:', err);
    }
  };

  const handleGitHubTokenChange = (event: ChangeEvent<HTMLInputElement>) => {
    const nextToken = event.target.value;
    setGithubToken(nextToken);
    persistGitHubToken(nextToken.trim());
    setGithubError(null);
  };

  const handlePublishToGitHub = async () => {
    if (!hasSelection) {
      return;
    }

    const token = githubToken.trim();
    if (!token) {
      setGithubError('Add a GitHub token with gist scope to publish.');
      return;
    }

    const output = buildOutput(undefined, fileName);
    if (!output) {
      return;
    }

    setIsPublishing(true);
    setGithubError(null);
    setGithubRawUrl(null);
    setGithubViewUrl(null);

    try {
      const result = await createGitHubGist(token, output.chosenName, output.content);
      setGithubRawUrl(result.rawUrl);
      setGithubViewUrl(result.htmlUrl);
      playSelect();
    } catch (err) {
      const message =
        err instanceof Error ? err.message : 'Failed to publish config to GitHub.';
      setGithubError(message);
    } finally {
      setIsPublishing(false);
    }
  };

  useEffect(() => {
    if (typeof window === 'undefined') {
      return;
    }

    const params = new URLSearchParams(window.location.search);
    const preset = params.get('preset');
    const name = sanitizeFileName(params.get('name'));
    const download = params.get('download') === '1';

    if (preset) {
      const ids = preset
        .split(',')
        .map((id) => id.trim())
        .filter((id) => id && allBlockIds.has(id));
      if (ids.length) {
        setSelectedIds(new Set(ids));
      }
    }

    if (name) {
      setPresetName(name);
    }

    if (download) {
      setAutoDownload(true);
    }
  }, []);

  useEffect(() => {
    setFileName(null);
    setDownloadUrl(null);
    setShareUrl(null);
    setGithubRawUrl(null);
    setGithubViewUrl(null);
    setGithubError(null);
  }, [selectedIds]);

  useEffect(() => {
    if (!autoDownload || autoGeneratedRef.current || !selectedBlocks.length) {
      return;
    }

    handleGenerate(presetName ?? undefined, true);
    autoGeneratedRef.current = true;
  }, [autoDownload, presetName, selectedBlocks, handleGenerate]);

  return (
    <>
      <ConsoleSection title="Config Builder">
        <p className="mb-4 text-xs md:text-sm">
          Select the modules you want, then generate a unique <span className="text-cs-yellow">.cfg</span> file.
          Publish it to GitHub to get a permanent download link for your teammates.
        </p>

        <div className="grid gap-4 md:grid-cols-2">
          {configGroups.map((group) => (
            <div
              key={group.id}
              className="bg-cs-dark border border-cs-green/30 p-4"
            >
              <div className="mb-3">
                <h3 className="text-cs-yellow text-xs md:text-sm font-bold uppercase tracking-wider">
                  {group.title}
                </h3>
                <p className="text-[10px] md:text-xs text-cs-gray mt-1">
                  {group.description}
                </p>
              </div>
              <div className="space-y-2">
                {group.blocks.map((block) => (
                  <label
                    key={block.id}
                    className="flex items-start gap-2 text-xs md:text-sm cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      className="mt-0.5 h-4 w-4 accent-cs-green bg-cs-black border border-cs-green/50"
                      checked={selectedIds.has(block.id)}
                      onChange={() => handleToggle(block.id)}
                    />
                    <span>
                      <span className="text-cs-green block">{block.label}</span>
                      <span className="text-[10px] md:text-xs text-cs-gray">
                        {block.description}
                      </span>
                    </span>
                  </label>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-2">
          <button
            type="button"
            className="cs-button text-[10px] md:text-xs disabled:opacity-50 disabled:cursor-not-allowed"
            onClick={handleSelectAll}
          >
            Select All
          </button>
          <button
            type="button"
            className="cs-button text-[10px] md:text-xs disabled:opacity-50 disabled:cursor-not-allowed"
            onClick={handleClear}
          >
            Clear
          </button>
          <button
            type="button"
            className="cs-button text-[10px] md:text-xs disabled:opacity-50 disabled:cursor-not-allowed"
            onClick={() => handleGenerate()}
            disabled={!hasSelection}
          >
            Generate .cfg
          </button>
          <span className="text-[10px] md:text-xs text-cs-gray ml-auto">
            {selectedBlocks.length} selected
          </span>
        </div>
      </ConsoleSection>

      <ConsoleSection title="Generated Output">
        {!hasSelection && (
          <p className="text-xs md:text-sm text-cs-gray">
            Select at least one module to preview and generate your config.
          </p>
        )}

        {hasSelection && (
          <>
            <div className="mb-4">
              <CodeBlock code={previewContent} title="Preview" />
            </div>

            <div className="bg-cs-dark border border-cs-green/30 p-4">
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
                <div>
                  <p className="text-[10px] md:text-xs text-cs-gray">Unique file name</p>
                  <p className="text-cs-yellow text-xs md:text-sm font-mono">
                    {fileName ?? 'Not generated yet'}
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <button
                    type="button"
                    className="cs-button text-[10px] md:text-xs disabled:opacity-50 disabled:cursor-not-allowed"
                    onClick={() => handleGenerate()}
                    disabled={!hasSelection}
                  >
                    Generate Again
                  </button>
                  {downloadUrl && fileName && (
                    <a
                      className="cs-button text-[10px] md:text-xs inline-flex items-center gap-1"
                      href={downloadUrl}
                      download={fileName}
                    >
                      <Download size={12} />
                      Download .cfg
                    </a>
                  )}
                </div>
              </div>

              {!downloadUrl && (
                <p className="mt-3 text-[10px] md:text-xs text-cs-gray">
                  Generate the config to get your download link, exec command, and GitHub publishing.
                </p>
              )}

              {downloadUrl && fileName && (
                <>
                  <div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] md:text-xs">
                    <span className="text-cs-gray">Console exec:</span>
                    <span className="text-cs-green font-mono">exec {fileName}</span>
                    <button
                      type="button"
                      className="cs-button text-[10px] md:text-xs px-2 py-1"
                      onClick={handleCopyExec}
                    >
                      {copiedExec ? (
                        <>
                          <Check size={12} />
                          Copied
                        </>
                      ) : (
                        <>
                          <Copy size={12} />
                          Copy
                        </>
                      )}
                    </button>
                  </div>

                  {shareUrl && (
                    <div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] md:text-xs">
                      <span className="text-cs-gray">Builder link:</span>
                      <input
                        className="flex-1 min-w-[200px] bg-cs-black border border-cs-green/30 text-cs-green px-2 py-1 text-[10px] md:text-xs"
                        value={shareUrl}
                        readOnly
                      />
                      <button
                        type="button"
                        className="cs-button text-[10px] md:text-xs px-2 py-1"
                        onClick={handleCopyShare}
                      >
                        {copiedShare ? (
                          <>
                            <Check size={12} />
                            Copied
                          </>
                        ) : (
                          <>
                            <LinkIcon size={12} />
                            Copy Link
                          </>
                        )}
                      </button>
                    </div>
                  )}

                  <div className="mt-4 border-t border-cs-green/20 pt-3">
                    <p className="text-[10px] md:text-xs text-cs-gray">
                      Publish a static <span className="text-cs-yellow">.cfg</span> file as a public GitHub Gist.
                    </p>
                    <label className="mt-2 block text-[10px] md:text-xs text-cs-gray">
                      GitHub token (gist scope)
                      <input
                        type="password"
                        className="mt-1 w-full bg-cs-black border border-cs-green/30 text-cs-green px-2 py-2 text-xs md:text-sm"
                        value={githubToken}
                        onChange={handleGitHubTokenChange}
                        placeholder="ghp_..."
                      />
                    </label>
                    {githubError && (
                      <p className="mt-2 text-[10px] md:text-xs text-cs-orange">{githubError}</p>
                    )}
                    <div className="mt-3 flex flex-wrap items-center gap-2">
                      <button
                        type="button"
                        className="cs-button text-[10px] md:text-xs disabled:opacity-50 disabled:cursor-not-allowed"
                        onClick={handlePublishToGitHub}
                        disabled={!hasSelection || !githubToken.trim() || isPublishing}
                      >
                        {isPublishing ? 'Publishing...' : 'Publish to GitHub'}
                      </button>
                      {githubViewUrl && (
                        <a
                          className="cs-button text-[10px] md:text-xs inline-flex items-center gap-1"
                          href={githubViewUrl}
                          target="_blank"
                          rel="noreferrer"
                        >
                          View Gist
                        </a>
                      )}
                    </div>
                    {githubRawUrl && (
                      <div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] md:text-xs">
                        <span className="text-cs-gray">GitHub raw link:</span>
                        <input
                          className="flex-1 min-w-[200px] bg-cs-black border border-cs-green/30 text-cs-green px-2 py-1 text-[10px] md:text-xs"
                          value={githubRawUrl}
                          readOnly
                        />
                        <button
                          type="button"
                          className="cs-button text-[10px] md:text-xs px-2 py-1"
                          onClick={handleCopyGitHub}
                        >
                          {copiedGitHub ? (
                            <>
                              <Check size={12} />
                              Copied
                            </>
                          ) : (
                            <>
                              <LinkIcon size={12} />
                              Copy Link
                            </>
                          )}
                        </button>
                      </div>
                    )}
                    <p className="mt-2 text-[10px] md:text-xs text-cs-gray">
                      Your token is stored locally in this browser. Clear the field to remove it.
                    </p>
                  </div>

                  <div className="mt-3 text-[10px] md:text-xs text-cs-gray space-y-1">
                    <p>1) Download the file and place it in your <span className="text-cs-yellow">cstrike</span> folder.</p>
                    <p>2) Open the game console and run <span className="text-cs-green">exec {fileName}</span>.</p>
                    <p>If auto-download is blocked, use the Download button above.</p>
                    <p>If you publish to GitHub, share the raw link for direct downloads.</p>
                  </div>
                </>
              )}
            </div>
          </>
        )}
      </ConsoleSection>
    </>
  );
}
