import { useEffect, useMemo, useState, type ChangeEvent } from 'react';
import { Check, Copy, Download, Eye, EyeOff, Link as LinkIcon, Save } from 'lucide-react';
import { ConsoleSection } from './ConsoleSection';
import { CodeBlock } from './CodeBlock';
import { useMenuSound } from '../hooks/useMenuSound';
import { createGitHubGist, persistGitHubToken, readGitHubToken } from '../utils/github';

type SavedConfig = {
  id: string;
  name: string;
  content: string;
  createdAt: string;
};

const STORAGE_KEY = 'cs16.customConfigs';

const generateId = () =>
  typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;

const readFromStorage = (): SavedConfig[] => {
  if (typeof window === 'undefined') {
    return [];
  }

  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      return [];
    }
    const parsed = JSON.parse(raw) as SavedConfig[];
    if (!Array.isArray(parsed)) {
      return [];
    }
    return parsed.filter((item) => item && item.id && item.name && item.content);
  } catch (err) {
    console.error('Failed to read custom configs:', err);
    return [];
  }
};

const writeToStorage = (configs: SavedConfig[]) => {
  if (typeof window === 'undefined') {
    return;
  }

  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(configs));
  } catch (err) {
    console.error('Failed to save custom configs:', err);
  }
};

type PublishedConfig = {
  rawUrl: string;
  htmlUrl: string | null;
  fileName: string;
};

const sanitizeFileName = (value?: string | null) => {
  if (!value) {
    return null;
  }

  const trimmed = value.trim();
  if (!trimmed) {
    return null;
  }

  const cleaned = trimmed
    .replace(/\.cfg$/i, '')
    .replace(/[^a-zA-Z0-9-_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  if (!cleaned) {
    return null;
  }

  return `${cleaned.slice(0, 48)}.cfg`;
};

const buildFileName = (config: SavedConfig) => {
  const sanitized = sanitizeFileName(config.name);
  const idChunk = config.id.split('-')[0] ?? config.id;
  const safeChunk = idChunk.replace(/[^a-zA-Z0-9]/g, '').slice(0, 8);
  const suffix = safeChunk || config.id.slice(0, 8);
  if (sanitized) {
    const base = sanitized.replace(/\.cfg$/i, '');
    return `${base}-${suffix}.cfg`;
  }

  return `cs16-${suffix}.cfg`;
};

const buildDownloadContent = (config: SavedConfig) => {
  const header = [
    '// Generated by CS 1.6 Config Wiki',
    `// Preset: ${config.name}`,
    `// Build: ${new Date().toISOString()}`,
    '',
  ].join('\n');
  const body = config.content.trim();
  return `${header}${body ? `\n${body}` : ''}\n`;
};

export function CustomConfigVault() {
  const { playSelect } = useMenuSound();
  const [configs, setConfigs] = useState<SavedConfig[]>([]);
  const [name, setName] = useState('');
  const [content, setContent] = useState('');
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [githubToken, setGithubToken] = useState(() => readGitHubToken());
  const [publishingId, setPublishingId] = useState<string | null>(null);
  const [publishedLinks, setPublishedLinks] = useState<Record<string, PublishedConfig>>({});
  const [publishError, setPublishError] = useState<string | null>(null);
  const [copiedLinkId, setCopiedLinkId] = useState<string | null>(null);
  const [copiedExecId, setCopiedExecId] = useState<string | null>(null);

  useEffect(() => {
    setConfigs(readFromStorage());
  }, []);

  const sortedConfigs = useMemo(
    () =>
      [...configs].sort(
        (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
      ),
    [configs],
  );

  const canSave = name.trim().length > 0 && content.trim().length > 0;
  const hasToken = githubToken.trim().length > 0;

  const handleSave = () => {
    const trimmedName = name.trim();
    const trimmedContent = content.trim();

    if (!trimmedName || !trimmedContent) {
      setError('Name and config body are required.');
      return;
    }

    const newConfig: SavedConfig = {
      id: generateId(),
      name: trimmedName.slice(0, 64),
      content: trimmedContent,
      createdAt: new Date().toISOString(),
    };

    const next = [newConfig, ...configs];
    setConfigs(next);
    writeToStorage(next);
    setName('');
    setContent('');
    setError(null);
    playSelect();
  };

  const handleToggle = (id: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
    playSelect();
  };

  const handleCopy = async (config: SavedConfig) => {
    try {
      await navigator.clipboard.writeText(config.content);
      setCopiedId(config.id);
      setTimeout(() => setCopiedId(null), 1500);
      playSelect();
    } catch (err) {
      console.error('Failed to copy config:', err);
    }
  };

  const handleDownload = (config: SavedConfig) => {
    const fileName = buildFileName(config);
    const contentToDownload = buildDownloadContent(config);
    const blob = new Blob([contentToDownload], { type: 'text/plain;charset=utf-8' });
    const blobUrl = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = blobUrl;
    anchor.download = fileName;
    anchor.rel = 'noopener';
    anchor.click();
    URL.revokeObjectURL(blobUrl);
    playSelect();
  };

  const handleCopyExec = async (fileName: string, configId: string) => {
    try {
      await navigator.clipboard.writeText(`exec ${fileName}`);
      setCopiedExecId(configId);
      setTimeout(() => setCopiedExecId(null), 1500);
      playSelect();
    } catch (err) {
      console.error('Failed to copy exec command:', err);
    }
  };

  const handleCopyLink = async (configId: string) => {
    const rawUrl = publishedLinks[configId]?.rawUrl;
    if (!rawUrl) {
      return;
    }

    try {
      await navigator.clipboard.writeText(rawUrl);
      setCopiedLinkId(configId);
      setTimeout(() => setCopiedLinkId(null), 1500);
      playSelect();
    } catch (err) {
      console.error('Failed to copy GitHub link:', err);
    }
  };

  const handleGitHubTokenChange = (event: ChangeEvent<HTMLInputElement>) => {
    const nextToken = event.target.value;
    setGithubToken(nextToken);
    persistGitHubToken(nextToken.trim());
    setPublishError(null);
  };

  const handlePublish = async (config: SavedConfig) => {
    const token = githubToken.trim();
    if (!token) {
      setPublishError('Add a GitHub token with gist scope to publish.');
      return;
    }

    const fileName = buildFileName(config);
    const contentToPublish = buildDownloadContent(config);

    setPublishingId(config.id);
    setPublishError(null);

    try {
      const result = await createGitHubGist(token, fileName, contentToPublish);
      setPublishedLinks((prev) => ({
        ...prev,
        [config.id]: {
          rawUrl: result.rawUrl,
          htmlUrl: result.htmlUrl,
          fileName,
        },
      }));
      playSelect();
    } catch (err) {
      const message =
        err instanceof Error ? err.message : 'Failed to publish config to GitHub.';
      setPublishError(message);
    } finally {
      setPublishingId(null);
    }
  };

  return (
    <>
      <ConsoleSection title="Custom Config Vault">
        <p className="mb-4 text-xs md:text-sm">
          Write your own config, give it a name, and store it inside the site. Publish to GitHub
          to make it permanent and shareable as a downloadable <span className="text-cs-yellow">.cfg</span>.
        </p>

        <div className="grid gap-4 md:grid-cols-[1fr_1.4fr]">
          <div className="bg-cs-dark border border-cs-green/30 p-4">
            <label className="block text-[10px] md:text-xs text-cs-gray mb-2">
              Config name
              <input
                className="mt-1 w-full bg-cs-black border border-cs-green/30 text-cs-green px-2 py-2 text-xs md:text-sm"
                value={name}
                onChange={(event) => setName(event.target.value)}
                placeholder="my-awp-config"
              />
            </label>
            <label className="block text-[10px] md:text-xs text-cs-gray">
              Config content
              <textarea
                className="mt-1 w-full min-h-[160px] bg-cs-black border border-cs-green/30 text-cs-green px-2 py-2 text-xs md:text-sm font-mono"
                value={content}
                onChange={(event) => setContent(event.target.value)}
                placeholder='bind "q" "lastinv"'
              />
            </label>
            {error && (
              <p className="mt-2 text-[10px] md:text-xs text-cs-orange">{error}</p>
            )}
            <button
              type="button"
              className="mt-3 cs-button text-[10px] md:text-xs disabled:opacity-50 disabled:cursor-not-allowed"
              onClick={handleSave}
              disabled={!canSave}
            >
              <Save size={12} className="inline mr-1" />
              Save Config
            </button>
            <div className="mt-4 border-t border-cs-green/20 pt-3">
              <p className="text-[10px] md:text-xs text-cs-gray">
                Publish saved configs to GitHub Gist for a permanent download link.
              </p>
              <label className="mt-2 block text-[10px] md:text-xs text-cs-gray">
                GitHub token (gist scope)
                <input
                  type="password"
                  className="mt-1 w-full bg-cs-black border border-cs-green/30 text-cs-green px-2 py-2 text-xs md:text-sm"
                  value={githubToken}
                  onChange={handleGitHubTokenChange}
                  placeholder="ghp_..."
                />
              </label>
              {publishError && (
                <p className="mt-2 text-[10px] md:text-xs text-cs-orange">{publishError}</p>
              )}
              <p className="mt-2 text-[10px] md:text-xs text-cs-gray">
                Your token is stored locally in this browser. Clear the field to remove it.
              </p>
            </div>
          </div>

          <div className="bg-cs-dark border border-cs-green/30 p-4">
            <p className="text-[10px] md:text-xs text-cs-gray mb-3">
              Saved configs: <span className="text-cs-yellow">{sortedConfigs.length}</span>
            </p>
            {sortedConfigs.length === 0 ? (
              <p className="text-xs md:text-sm text-cs-gray">
                No custom configs yet. Save one to see it here.
              </p>
            ) : (
              <div className="space-y-3">
                {sortedConfigs.map((config) => {
                  const isExpanded = expandedIds.has(config.id);
                  const isCopied = copiedId === config.id;
                  const fileName = buildFileName(config);
                  const published = publishedLinks[config.id];
                  const isPublishing = publishingId === config.id;
                  const isLinkCopied = copiedLinkId === config.id;
                  const isExecCopied = copiedExecId === config.id;
                  return (
                    <div
                      key={config.id}
                      className="border border-cs-green/20 bg-cs-black/60 p-3"
                    >
                      <div className="flex flex-wrap items-center justify-between gap-2">
                        <div>
                          <p className="text-cs-green text-xs md:text-sm font-bold">
                            {config.name}
                          </p>
                          <p className="text-[10px] md:text-xs text-cs-gray">
                            {new Date(config.createdAt).toLocaleString()}
                          </p>
                        </div>
                        <div className="flex flex-wrap items-center gap-2">
                          <button
                            type="button"
                            className="cs-button text-[10px] md:text-xs px-2 py-1"
                            onClick={() => handleToggle(config.id)}
                          >
                            {isExpanded ? (
                              <>
                                <EyeOff size={12} className="inline mr-1" />
                                Hide
                              </>
                            ) : (
                              <>
                                <Eye size={12} className="inline mr-1" />
                                View
                              </>
                            )}
                          </button>
                          <button
                            type="button"
                            className="cs-button text-[10px] md:text-xs px-2 py-1"
                            onClick={() => handleCopy(config)}
                          >
                            {isCopied ? (
                              <>
                                <Check size={12} className="inline mr-1" />
                                Copied
                              </>
                            ) : (
                              <>
                                <Copy size={12} className="inline mr-1" />
                                Copy
                              </>
                            )}
                          </button>
                          <button
                            type="button"
                            className="cs-button text-[10px] md:text-xs px-2 py-1"
                            onClick={() => handleDownload(config)}
                          >
                            <Download size={12} className="inline mr-1" />
                            Download
                          </button>
                          <button
                            type="button"
                            className="cs-button text-[10px] md:text-xs px-2 py-1 disabled:opacity-50 disabled:cursor-not-allowed"
                            onClick={() => handlePublish(config)}
                            disabled={!hasToken || isPublishing}
                          >
                            <LinkIcon size={12} className="inline mr-1" />
                            {isPublishing ? 'Publishing...' : published ? 'Republish' : 'Publish'}
                          </button>
                        </div>
                      </div>

                      {isExpanded && (
                        <div className="mt-3">
                          <CodeBlock code={config.content} title={config.name} />
                          <div className="mt-3 space-y-2 text-[10px] md:text-xs">
                            <div className="flex flex-wrap items-center gap-2">
                              <span className="text-cs-gray">Console exec:</span>
                              <span className="text-cs-green font-mono">exec {fileName}</span>
                              <button
                                type="button"
                                className="cs-button text-[10px] md:text-xs px-2 py-1"
                                onClick={() => handleCopyExec(fileName, config.id)}
                              >
                                {isExecCopied ? (
                                  <>
                                    <Check size={12} />
                                    Copied
                                  </>
                                ) : (
                                  <>
                                    <Copy size={12} />
                                    Copy
                                  </>
                                )}
                              </button>
                            </div>
                            {published ? (
                              <div className="space-y-2">
                                <div className="flex flex-wrap items-center gap-2">
                                  <span className="text-cs-gray">GitHub raw link:</span>
                                  <input
                                    className="flex-1 min-w-[200px] bg-cs-black border border-cs-green/30 text-cs-green px-2 py-1 text-[10px] md:text-xs"
                                    value={published.rawUrl}
                                    readOnly
                                  />
                                  <button
                                    type="button"
                                    className="cs-button text-[10px] md:text-xs px-2 py-1"
                                    onClick={() => handleCopyLink(config.id)}
                                  >
                                    {isLinkCopied ? (
                                      <>
                                        <Check size={12} />
                                        Copied
                                      </>
                                    ) : (
                                      <>
                                        <LinkIcon size={12} />
                                        Copy Link
                                      </>
                                    )}
                                  </button>
                                </div>
                                {published.htmlUrl && (
                                  <a
                                    className="cs-button text-[10px] md:text-xs inline-flex items-center gap-1"
                                    href={published.htmlUrl}
                                    target="_blank"
                                    rel="noreferrer"
                                  >
                                    View Gist
                                  </a>
                                )}
                              </div>
                            ) : (
                              <p className="text-cs-gray">
                                Publish to GitHub to get a permanent download link.
                              </p>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </ConsoleSection>
    </>
  );
}
