const GITHUB_TOKEN_STORAGE_KEY = 'cs16.githubToken';

type GitHubGistResponse = {
  html_url?: string;
  files?: Record<string, { raw_url?: string }>;
  message?: string;
};

export const readGitHubToken = () => {
  if (typeof window === 'undefined') {
    return '';
  }

  try {
    return window.localStorage.getItem(GITHUB_TOKEN_STORAGE_KEY) ?? '';
  } catch (err) {
    console.error('Failed to read GitHub token:', err);
    return '';
  }
};

export const persistGitHubToken = (token: string) => {
  if (typeof window === 'undefined') {
    return;
  }

  try {
    if (!token) {
      window.localStorage.removeItem(GITHUB_TOKEN_STORAGE_KEY);
    } else {
      window.localStorage.setItem(GITHUB_TOKEN_STORAGE_KEY, token);
    }
  } catch (err) {
    console.error('Failed to save GitHub token:', err);
  }
};

export const createGitHubGist = async (
  token: string,
  fileName: string,
  content: string,
) => {
  const response = await fetch('https://api.github.com/gists', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      description: 'CS 1.6 config generated by CS 1.6 Config Wiki',
      public: true,
      files: {
        [fileName]: { content },
      },
    }),
  });

  let payload: GitHubGistResponse | null = null;
  try {
    payload = (await response.json()) as GitHubGistResponse;
  } catch (err) {
    console.error('Failed to parse GitHub response:', err);
  }

  if (!response.ok) {
    const message = payload?.message ?? `GitHub API error (${response.status})`;
    throw new Error(message);
  }

  const rawUrl = payload?.files?.[fileName]?.raw_url;
  if (!rawUrl) {
    throw new Error('GitHub did not return a raw file link.');
  }

  return { rawUrl, htmlUrl: payload?.html_url ?? null };
};
